---
# LoadBalancer Service for external DNS access
# This file is separate to allow flexible deployment strategies
#
# Deploy after the main deployment is ready:
# kubectl apply -f k8s-loadbalancer.yaml
#
apiVersion: v1
kind: Service
metadata:
  name: jw238dns-lb
  namespace: jw238dns
  labels:
    app: jw238dns
  annotations:
    # AWS NLB configuration
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"

    # Preserve client source IP
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: dns-udp
      port: 53
      targetPort: dns-udp
      protocol: UDP
  selector:
    app: jw238dns
